// register-gen 扫描 internal/api/v1/ 下的 *_grpc.pb.go 文件，
// 自动生成 router_gen.go，聚合所有服务的 gRPC + HTTP 网关注册。
//
// 使用方式：go run ./cmd/register-gen/
// 建议加入 Makefile：gen-register: go run ./cmd/register-gen/
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ServiceInfo 描述一个需要注册的 gRPC 服务
type ServiceInfo struct {
	ProtoPkg    string // 短包名，如 "hello"
	RegFunc     string // gRPC 注册函数，如 "RegisterHelloServiceServer"
	GatewayFunc string // HTTP 网关注册函数，如 "RegisterHelloServiceHandlerFromEndpoint"
	ImportPath  string // proto 包导入路径
	ImplPath    string // service 实现包导入路径
}

func main() {
	const module = "go-project-template"
	protoDir := filepath.Join("internal", "api", "v1")
	outputFile := filepath.Join("cmd", "router_gen.go")

	var services []ServiceInfo

	entries, err := os.ReadDir(protoDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read dir %s: %v\n", protoDir, err)
		os.Exit(1)
	}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		dir := entry.Name()
		grpcFile := filepath.Join(protoDir, dir, dir+"_grpc.pb.go")
		info, err := parseGrpcFile(grpcFile)
		if err != nil {
			// 跳过没有 *_grpc.pb.go 的目录（如 apidocs.swagger.json 所在目录）
			continue
		}
		info.ImportPath = module + "/" + filepath.ToSlash(filepath.Join(protoDir, dir))
		info.ImplPath = module + "/internal/service/" + dir
		services = append(services, info)
	}

	if len(services) == 0 {
		fmt.Println("no services found, skip generating")
		return
	}

	if err := generate(outputFile, services); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s with %d service(s)\n", outputFile, len(services))
}

// parseGrpcFile 解析 *_grpc.pb.go，提取包名和 Register*Server 函数名
func parseGrpcFile(path string) (ServiceInfo, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.PackageClauseOnly)
	if err != nil {
		return ServiceInfo{}, err
	}

	info := ServiceInfo{
		ProtoPkg: f.Name.Name,
	}

	// 重新解析，获取所有顶层声明
	fset2 := token.NewFileSet()
	f2, err := parser.ParseFile(fset2, path, nil, 0)
	if err != nil {
		return ServiceInfo{}, err
	}

	for _, decl := range f2.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !fn.Name.IsExported() {
			continue
		}
		name := fn.Name.Name
		if strings.HasPrefix(name, "Register") && strings.HasSuffix(name, "Server") {
			info.RegFunc = name
			// RegisterHelloServiceServer → RegisterHelloServiceHandlerFromEndpoint
			info.GatewayFunc = strings.TrimSuffix(name, "Server") + "HandlerFromEndpoint"
			break
		}
	}

	if info.RegFunc == "" {
		return ServiceInfo{}, fmt.Errorf("no Register*Server function found in %s", path)
	}
	return info, nil
}

func generate(outputFile string, services []ServiceInfo) error {
	tmpl := template.Must(template.New("router_gen").Parse(`// Code generated by cmd/register-gen; DO NOT EDIT.

package main

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
{{- range . }}
	{{ .ProtoPkg }}Pb "{{ .ImportPath }}"
	{{ .ProtoPkg }}Impl "{{ .ImplPath }}"
{{- end }}
)

// registerGRPCServices 注册所有 gRPC 服务
func registerGRPCServices(s *grpc.Server) {
{{- range . }}
	{{ .ProtoPkg }}Pb.{{ .RegFunc }}(s, {{ .ProtoPkg }}Impl.NewService())
{{- end }}
}

// registerHTTPHandlers 注册所有 HTTP 网关
func registerHTTPHandlers(ctx context.Context, mux *runtime.ServeMux, grpcAddr string, opts []grpc.DialOption) error {
{{- range . }}
	if err := {{ .ProtoPkg }}Pb.{{ .GatewayFunc }}(ctx, mux, grpcAddr, opts); err != nil {
		return err
	}
{{- end }}
	return nil
}
`))

	f, err := os.Create(outputFile)
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, services)
}
