// Code generated by cmd/register-gen; DO NOT EDIT.

package main

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	helloPb "go-project-template/internal/api/v1/hello"
	helloImpl "go-project-template/internal/service/hello"
	"google.golang.org/grpc"
)

// registerGRPCServices 注册所有 gRPC 服务
func registerGRPCServices(s *grpc.Server) {
	helloPb.RegisterHelloServiceServer(s, helloImpl.NewService())
}

// registerHTTPHandlers 注册所有 HTTP 网关
func registerHTTPHandlers(ctx context.Context, mux *runtime.ServeMux, grpcAddr string, opts []grpc.DialOption) error {
	if err := helloPb.RegisterHelloServiceHandlerFromEndpoint(ctx, mux, grpcAddr, opts); err != nil {
		return err
	}
	return nil
}
